AWSTemplateFormatVersion: 2010-09-09

Description: my s3 bucket

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: std21004

  BucketSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["", [td1, -s3, -bucket]]
      Type: String
      Value: !GetAtt S3Bucket.Arn
