AWSTemplateFormatVersion: 2010-09-09

Description: my s3 bucket

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: Std21004

  BucketS3:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: MybucketS3
      Type: String
      Value: !GetAtt S3Bucket.Arn

  MyBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: Mybucket
      Type: String
      Value: "my-bucket-name"

  BucketSSM:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: Mybucket
      Type: String
      Value: !GetAtt MyBucket.Value
